In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

x = np.array(my_list)

type(x)


numpy.ndarray

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

np.array(my_matrix)

list(range(0,5))

np.arange(0,5)

np.zeros(3)

array([ 0.,  0.,  0.])

In [4]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [5]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [6]:
np.ones((3,8))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [7]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [8]:
np.linspace(0,10,30)

array([  0.        ,   0.34482759,   0.68965517,   1.03448276,
         1.37931034,   1.72413793,   2.06896552,   2.4137931 ,
         2.75862069,   3.10344828,   3.44827586,   3.79310345,
         4.13793103,   4.48275862,   4.82758621,   5.17241379,
         5.51724138,   5.86206897,   6.20689655,   6.55172414,
         6.89655172,   7.24137931,   7.5862069 ,   7.93103448,
         8.27586207,   8.62068966,   8.96551724,   9.31034483,
         9.65517241,  10.        ])

In [9]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [10]:
# uniform distribution
np.random.rand(5,4)

array([[ 0.49783115,  0.01009794,  0.19783819,  0.93297482],
       [ 0.30447183,  0.44458574,  0.37714326,  0.44332879],
       [ 0.51154343,  0.21066577,  0.42860607,  0.2510948 ],
       [ 0.56527295,  0.37878604,  0.36221962,  0.21282642],
       [ 0.11695719,  0.92448204,  0.45568198,  0.20500848]])

In [11]:
# standard normal distribution - Gaussian Distribution
np.random.randn(5,4)

array([[-1.07260247,  0.71583033, -0.86880994,  0.16009125],
       [ 0.17914863,  0.07026722,  0.89419365, -1.30550294],
       [ 1.49518776,  0.51827001,  0.73988646, -0.65954251],
       [-1.03072967, -0.54071566,  0.71955717,  0.55874155],
       [ 0.12525022,  0.12381355,  0.25857726,  0.49856944]])

In [12]:
np.random.randint(1,100)

37

In [14]:
np.random.randint(1,100,2)

array([51, 73])

In [15]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
ranarr = np.random.randint(0,50,10)
ranarr

array([35, 21,  5, 34, 39, 44, 41,  0, 24,  0])

In [18]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr.dtype

dtype('int64')

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.argmin()

0