In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#Broadcasting
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
slice_of_arr = arr[0:6]

In [11]:
slice_of_arr[:] = 99

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy()

In [18]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [23]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
mat[0]

array([ 5, 10, 15])

In [25]:
mat[2]

array([35, 40, 45])

In [26]:
mat[1][1]

25

In [27]:
mat[1,1]

25

In [28]:
mat[0,2]

15

In [29]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [30]:
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [31]:
#Conditional Selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [33]:
bool_arr = arr > 4

In [34]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [35]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
arr[arr <= 9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])